---

- name: "Install Ruby 2.0"
  become: yes
  apt:
    name="{{ item }}"
    state="present"
    update_cache="yes"
  with_items:
    - ruby2.0
    - ruby2.0-dev

- name: "Install Jekyll"
  gem:
    name="{{ item }}"
    state="present"
    executable="/usr/bin/gem2.0"
  with_items:
    - jekyll
    - bundler
